<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2013-05-06T07:12:03+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	$page_id    = 2;
	require('../index.php');
// *************************************************
