<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2013-02-19T07:16:27+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	header('HTTP/1.1 301 Moved Permanently');
	header('Location: http://4601.linux7.testsider.dk/index.php');
// *************************************************
