<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2013-05-06T06:32:18+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	header('HTTP/1.1 301 Moved Permanently');
	header('Location: http://www.hakoah.dk/test/index.php');
// *************************************************
