<?php
// *** This file is generated by WebsiteBaker Ver.2.8.3
// *** Creation date: 2013-12-08T15:49:25+00:00
// *** Do not modify this file manually
// *** WB will rebuild this file from time to time!!
// *************************************************
	$page_id    = 73;
	require('../../index.php');
// *************************************************
